version: "3"

services:
    webserver:
        build:
            context: .
        ports:
            - "8021:80"
        volumes:
            - "./ops/docker/php/xdebug.ini:/etc/php7/conf.d/02_xdebug.ini"
            - ./:/opt/app
        environment:
            APP_ENV: dev
    database:
        image: mysql/mysql-server:5.6
        volumes:
            - "./ops/docker/mysql/raw:/var/lib/mysql"
            - "./ops/docker/mysql/conf/my.cnf:/etc/my.cnf"
        environment:
            - "MYSQL_DATABASE=docker_test"
            - "MYSQL_ROOT_PASSWORD=password"
            - "MYSQL_ROOT_HOST=%"
        ports:
            - "33063:3306"
    redis:
        image: redis:alpine
        ports:
            - "63793:6379"
